package dev.icehunter.fornax.pipeline;

import com.mojang.blaze3d.GpuFormat;
import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.blaze3d.systems.CommandEncoder;
import com.mojang.blaze3d.systems.GpuDevice;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.textures.GpuTexture;
import com.mojang.blaze3d.textures.GpuTextureView;
import org.jspecify.annotations.Nullable;

/**
 * The engine-generated {@code builtin.noise} texture: a 512x512 RGBA8 tileable noise atlas,
 * regenerated identically every session from a fixed seed (never re-rolled, never pack-supplied).
 * Replaces the in-shader hash-lattice {@code cloud_noise3} the volumetric-clouds phase shipped with
 * a filtered texture lookup -- per-octave smoothness of LINEAR-filtered texture noise reads
 * noticeably better than computed lattice noise at the same cost, and this is the one engine asset
 * that technique needs (see the addendum plan this class implements, Task A).
 *
 * <p>Four independent channels, each generated by {@link #generatePixels()} (pure Java, no GPU
 * dependency -- see {@code NoiseTextureTest} for the properties this method is unit-tested
 * against):
 * <ul>
 *   <li>R -- smooth single-octave value noise, {@link #R_CELLS} lattice cells/tile.</li>
 *   <li>G -- smooth single-octave value noise, {@link #G_CELLS} lattice cells/tile (a different
 *       resolution AND a different salt from R, so the two channels are never the same pattern at
 *       a different frequency).</li>
 *   <li>B -- {@link #FBM_OCTAVES}-octave FBM (persistence {@link #FBM_PERSISTENCE}, base
 *       {@link #FBM_BASE_CELLS} cells -- cell counts double each octave: 8/16/32/64).</li>
 *   <li>A -- white noise (per-pixel hash, no lattice interpolation).</li>
 * </ul>
 *
 * <p>Every channel is built on one shared, tileable hash primitive ({@link #latticeHash}): the
 * lattice coordinate is wrapped ({@code Math.floorMod(coord, cells)}) BEFORE hashing, so the
 * function is exactly periodic with period {@code cells} in cell space (equivalently, period
 * {@link #SIZE} in pixel space for a channel whose cell count divides {@code SIZE} evenly -- true
 * for every channel here). This is what makes the texture safe to bind REPEAT: the lattice itself
 * wraps, not just the raw 512x512 canvas edge.
 *
 * <p>GPU side ({@link #getView()}/{@link #getTexture()}) is a lazy, once-per-session
 * create-and-upload, mirroring {@code VoxelDebugRaymarchPass.ensureDebugTexture}'s static-holder
 * shape: nothing is allocated until the graph first asks for {@code builtin.noise} (device exists
 * by the time any graph runs), and the same texture/view is returned for the rest of the session --
 * this asset is static content, never rebuilt like a per-frame render target. Upload mirrors
 * {@code MaterialMapAtlasReloadListener.upload}'s {@code NativeImage} path: a {@code
 * NativeImage.Format.RGBA} image is filled pixel-by-pixel via {@code setPixel} (confirmed by
 * javap of the deobfuscated jar to internally call {@code ARGB.toABGR} then {@code
 * setPixelABGR} -- i.e. it accepts the exact standard-Java ARGB {@code int} packing {@link
 * #generatePixels()} already produces, no separate byte-order translation needed), then handed to
 * {@code CommandEncoder.writeToTexture(GpuTexture, NativeImage)}. Uses {@code
 * RenderSystem.tryGetDevice()} (the null-safe accessor {@code TargetRegistry} already uses, not
 * {@code getDevice()}) so a call before a device exists (e.g. from a unit test) degrades to {@code
 * null} rather than throwing -- garbage-VRAM law: no half-initialized GPU state is ever left
 * behind by a failed attempt, {@link #texture}/{@link #view} are only assigned together once
 * upload fully succeeds.
 */
public final class NoiseTexture {
    /** Both dimensions of the generated texture. */
    public static final int SIZE = 512;

    /** R channel: single-octave value noise lattice resolution. */
    static final int R_CELLS = 16;
    /** G channel: single-octave value noise lattice resolution (deliberately != R_CELLS). */
    static final int G_CELLS = 32;
    /** B channel: FBM base-octave lattice resolution (cells double each octave). */
    static final int FBM_BASE_CELLS = 8;
    static final int FBM_OCTAVES = 4;
    static final float FBM_PERSISTENCE = 0.5f;

    /** Per-channel hash salts -- keeps R/G/B/A decorrelated even where lattice coordinates alias
     * across channels of different cell counts. Arbitrary, fixed, distinct. */
    static final int R_SALT = 0x51;
    static final int G_SALT = 0xA2;
    private static final int FBM_SALT_BASE = 0x10;
    private static final int WHITE_SALT = 0x7C;

    /** Fixed generator seed -- deterministic across every call/session, never re-rolled. */
    private static final long SEED = 0x9E3779B97F4A7C15L;

    @Nullable
    private static GpuTexture texture;
    @Nullable
    private static GpuTextureView view;

    private NoiseTexture() {
    }

    /**
     * Generates the full 512x512 ARGB {@code int[]} (standard Java packing: {@code 0xAARRGGBB}),
     * row-major, {@code pixels[y * SIZE + x]}. Pure function of the fixed seed -- see the class doc
     * on the four channels this fills. Called once per GPU upload ({@link #ensureCreated()}); also
     * the entire surface {@code NoiseTextureTest} exercises without any GPU device.
     */
    public static int[] generatePixels() {
        int[] pixels = new int[SIZE * SIZE];
        for (int y = 0; y < SIZE; y++) {
            for (int x = 0; x < SIZE; x++) {
                int r = toByte(channelValue(x, y, R_CELLS, R_SALT));
                int g = toByte(channelValue(x, y, G_CELLS, G_SALT));
                int b = toByte(fbmValue(x, y));
                int a = toByte(whiteValue(x, y));
                pixels[y * SIZE + x] = (a << 24) | (r << 16) | (g << 8) | b;
            }
        }
        return pixels;
    }

    /**
     * Bilinear-interpolated (smoothstepped) value noise for one channel at pixel {@code (px, py)},
     * lattice resolution {@code cells}, hash stream {@code salt}. Package-visible for direct
     * unit-testing of the tileability property ({@code channelValue(x, y, ...) ==
     * channelValue(x + SIZE, y, ...)}, exactly -- see {@link #latticeHash}'s wrap).
     */
    static float channelValue(int px, int py, int cells, int salt) {
        float fx = (float) px * cells / SIZE;
        float fy = (float) py * cells / SIZE;
        int ix0 = (int) Math.floor(fx);
        int iy0 = (int) Math.floor(fy);
        float tx = smooth(fx - ix0);
        float ty = smooth(fy - iy0);

        float v00 = latticeHash(ix0, iy0, cells, salt);
        float v10 = latticeHash(ix0 + 1, iy0, cells, salt);
        float v01 = latticeHash(ix0, iy0 + 1, cells, salt);
        float v11 = latticeHash(ix0 + 1, iy0 + 1, cells, salt);

        float a = lerp(v00, v10, tx);
        float b = lerp(v01, v11, tx);
        return lerp(a, b, ty);
    }

    /**
     * {@link #FBM_OCTAVES}-octave FBM at pixel {@code (px, py)}: cell counts double each octave
     * from {@link #FBM_BASE_CELLS} (8/16/32/64), amplitude falls off by {@link #FBM_PERSISTENCE}
     * each octave, normalized by total amplitude so the result stays in {@code [0, 1)}. Every
     * octave's cell count divides {@link #SIZE} evenly, so this wraps at a full-tile shift exactly
     * like {@link #channelValue} does.
     */
    static float fbmValue(int px, int py) {
        float sum = 0f;
        float amp = 1f;
        float totalAmp = 0f;
        int cells = FBM_BASE_CELLS;
        for (int octave = 0; octave < FBM_OCTAVES; octave++) {
            sum += amp * channelValue(px, py, cells, FBM_SALT_BASE + octave);
            totalAmp += amp;
            amp *= FBM_PERSISTENCE;
            cells *= 2;
        }
        return sum / totalAmp;
    }

    /**
     * White noise at pixel {@code (px, py)} -- a raw per-pixel hash, no lattice interpolation.
     * Reuses {@link #latticeHash} with {@code cells = SIZE} purely so the wrap (and therefore
     * tileability) falls out of the same shared primitive: {@code Math.floorMod(px, SIZE)} is the
     * identity for any {@code px} already in {@code [0, SIZE)}, so this is exactly a per-pixel hash
     * for in-range coordinates, and still provably wraps for the tileability test's shifted-by-a-
     * full-tile assertion.
     */
    static float whiteValue(int px, int py) {
        return latticeHash(px, py, SIZE, WHITE_SALT);
    }

    /**
     * Deterministic pseudo-random value in {@code [0, 1)} for lattice corner {@code (ix, iy)} at
     * resolution {@code cells}, hash stream {@code salt}. Wraps {@code ix}/{@code iy} via {@code
     * Math.floorMod(_, cells)} BEFORE hashing -- this single line is the entire tileability
     * guarantee: {@code latticeHash(ix, iy, cells, salt) == latticeHash(ix + cells, iy, cells,
     * salt)} exactly, for any {@code ix}/{@code iy}/{@code salt}, since {@code floorMod} is
     * periodic with period {@code cells}.
     */
    private static float latticeHash(int ix, int iy, int cells, int salt) {
        int wx = Math.floorMod(ix, cells);
        int wy = Math.floorMod(iy, cells);
        long z = SEED;
        z = mix64(z + wx * 0x9E3779B97F4A7C15L);
        z = mix64(z + wy * 0xC2B2AE3D27D4EB4FL);
        z = mix64(z + salt * 0x165667B19E3779F9L);
        return ((z >>> 40) & 0xFFFFFF) / (float) (1 << 24);
    }

    /** splitmix64-style avalanche mix -- gives {@link #latticeHash} good bit dispersion from the
     * small integer inputs (cell coordinates, salts) it combines. */
    private static long mix64(long z) {
        z = (z ^ (z >>> 30)) * 0xBF58476D1CE4E5B9L;
        z = (z ^ (z >>> 27)) * 0x94D049BB133111EBL;
        return z ^ (z >>> 31);
    }

    private static float smooth(float t) {
        return t * t * (3f - 2f * t);
    }

    private static float lerp(float a, float b, float t) {
        return a + (b - a) * t;
    }

    private static int toByte(float unit) {
        int v = Math.round(unit * 255f);
        return Math.max(0, Math.min(255, v));
    }

    /**
     * The noise texture's view, lazily created (and generated) on first call this session. {@code
     * null} only if no GPU device is available yet (see {@link #ensureCreated()}) -- never a
     * half-initialized texture.
     */
    @Nullable
    public static GpuTextureView getView() {
        ensureCreated();
        return view;
    }

    /** The noise texture itself -- see {@link #getView()}. */
    @Nullable
    public static GpuTexture getTexture() {
        ensureCreated();
        return texture;
    }

    private static void ensureCreated() {
        if (texture != null) {
            return;
        }
        GpuDevice device = RenderSystem.tryGetDevice();
        if (device == null) {
            return;
        }

        int[] pixels = generatePixels();
        try (NativeImage image = new NativeImage(NativeImage.Format.RGBA, SIZE, SIZE, false)) {
            for (int y = 0; y < SIZE; y++) {
                for (int x = 0; x < SIZE; x++) {
                    image.setPixel(x, y, pixels[y * SIZE + x]);
                }
            }

            GpuTexture newTexture = device.createTexture("Fornax Noise",
                    GpuTexture.USAGE_TEXTURE_BINDING | GpuTexture.USAGE_COPY_DST,
                    GpuFormat.RGBA8_UNORM, SIZE, SIZE, 1, 1);
            CommandEncoder encoder = device.createCommandEncoder();
            encoder.writeToTexture(newTexture, image);

            GpuTextureView newView;
            try {
                newView = device.createTextureView(newTexture);
            } catch (RuntimeException e) {
                // texture/view must assign together or not at all: a throw here left texture
                // already non-null while view stayed null, so the guard above never retried and
                // getView() silently returned null for the rest of the process.
                newTexture.close();
                throw e;
            }
            texture = newTexture;
            view = newView;
        }
    }
}
